<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add a new computer</name>
   <tag></tag>
   <elementGuidId>9794d813-587b-4d17-af2f-adbaa56b09ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Add a new computer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94ffe3ce-cfca-4eb3-996a-6c3aa7919f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn success</value>
      <webElementGuid>281ee214-ed2a-4b13-9ef0-4f748abcf4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>2946ce5b-d5ed-4521-aee2-08a53e82a7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/computers/new</value>
      <webElementGuid>5bfaf32b-7c61-42a8-bb62-447a407af004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add a new computer</value>
      <webElementGuid>a089d144-869d-423d-a004-ba68f90d9161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add&quot;)</value>
      <webElementGuid>36a3240f-f2fa-4104-a343-c2f0ca143c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='add']</value>
      <webElementGuid>fbea9fe7-8309-434e-9be2-a2f724057ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions']/form/a</value>
      <webElementGuid>5afd415b-3cdc-4d86-b10a-89f7da8a7e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add a new computer')]</value>
      <webElementGuid>ce8b20ed-0b12-4ec3-9a7a-9c837ed2da51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer database'])[1]/following::a[1]</value>
      <webElementGuid>7ff3b827-a693-4344-98a8-78629c5c2c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer name'])[1]/preceding::a[1]</value>
      <webElementGuid>6576333a-fd2b-4404-833f-535cdb5218fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduced'])[1]/preceding::a[2]</value>
      <webElementGuid>3aa1ed43-4c6b-4313-8348-c1baef79fd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add a new computer']/parent::*</value>
      <webElementGuid>59a6a426-1ab0-435b-ba2a-86fac0c002dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/computers/new')]</value>
      <webElementGuid>970466cd-3bf7-4946-ba16-579b9b277805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>433189dc-de04-4bf2-8213-689154cbebb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'add' and @href = '/computers/new' and (text() = 'Add a new computer' or . = 'Add a new computer')]</value>
      <webElementGuid>efd5e13e-1e4a-473e-9678-f3c77d3c5524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
