<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Discontinued_date</name>
   <tag></tag>
   <elementGuidId>d38681f4-0b39-4fb4-8f71-1ac52106f9f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#discontinued</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='discontinued']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Discontinued&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91e84424-13ec-47d2-b061-dd4482bb8f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2787539c-906e-426f-b322-f2e737d96c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discontinued</value>
      <webElementGuid>4a3c6cbc-a68a-4916-9f53-a8a2f379b667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>discontinued</value>
      <webElementGuid>e37e6b1a-9a0b-4e5d-9f87-567470cfd14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discontinued&quot;)</value>
      <webElementGuid>c52cbdd6-053d-456b-846a-2b20cce87a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='discontinued']</value>
      <webElementGuid>4295c3c4-4a40-4256-9626-4da73a4401d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[3]/div/input</value>
      <webElementGuid>a0d61755-8b7f-4811-88fc-15f80447122a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>b5d02c4d-fdcf-4f11-8048-a06d196ef877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'discontinued' and @name = 'discontinued']</value>
      <webElementGuid>9a1bdf83-0f4a-4381-a247-7da72ca049a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
