<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Introduced_date</name>
   <tag></tag>
   <elementGuidId>c4e60ea2-d280-47bc-b5aa-1702e2472699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#introduced</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='introduced']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Introduced&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ee353bc-0d38-4a59-9e3b-63fe677876ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5d1b718-6721-43dd-93b9-252646d693d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>introduced</value>
      <webElementGuid>8cf0c188-7603-4250-b0d9-0ed4297561f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>introduced</value>
      <webElementGuid>329e0c01-7162-47c3-a3df-9a9c39023d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;introduced&quot;)</value>
      <webElementGuid>8d48448b-ff70-4fc4-afa0-cf9554105219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='introduced']</value>
      <webElementGuid>5da8756d-174d-4707-afd3-d01a44cebfc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[2]/div/input</value>
      <webElementGuid>c982c254-32b1-43e7-b590-2f5bf69e281d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d8dc78a6-22a1-4999-84c4-643d12160d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'introduced' and @name = 'introduced']</value>
      <webElementGuid>ef500a36-35a4-48d8-85fe-8d19e3688e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
