<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//button[@type='submit']</description>
   <name>Submit</name>
   <tag></tag>
   <elementGuidId>9a270012-0c52-4e35-a509-f51c407d71b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
